# Generated by Selenium IDE
import os
import sys

from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By

from core.selenium.common import close_driver, initialize_driver

sys.path.append(os.getcwd())


class TestFakenodo:
    def setup_method(self, method):
        self.driver = initialize_driver()
        self.vars = {}

    def teardown_method(self, method):
        close_driver(self.driver)

    def test_fakenodo(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1920, 1080)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(6) .align-middle:nth-child(2)").click()
        self.driver.find_element(By.ID, "title").click()
        self.driver.find_element(By.ID, "title").send_keys("prueba fakenodo")
        self.driver.find_element(By.ID, "desc").click()
        self.driver.find_element(By.ID, "desc").send_keys("esto es una prueba")
        self.driver.find_element(By.ID, "myDropzone").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".dz-button")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.LINK_TEXT, "prueba fakenodo").click()
        self.driver.find_element(By.CSS_SELECTOR, "form > .btn").click()
