"""migracion del merge eca72

Revision ID: 187668a75f9a
Revises: eca72f93a3e4
Create Date: 2025-11-17 12:11:23.549805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '187668a75f9a'
down_revision = 'eca72f93a3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poke_filename', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('poke_version', sa.String(length=120), nullable=True))
        batch_op.drop_column('uvl_filename')
        batch_op.drop_column('uvl_version')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_two_factor_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('two_factor_recovery_codes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('two_factor_recovery_codes')
        batch_op.drop_column('two_factor_secret')
        batch_op.drop_column('is_two_factor_enabled')

    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uvl_version', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('poke_version')
        batch_op.drop_column('poke_filename')

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('download_count')

    # ### end Alembic commands ###
