"""eliminacion modulo featuremodel

Revision ID: 1e2ca7723141
Revises: 5a46707d932d
Create Date: 2025-11-15 15:30:46.124447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e2ca7723141'
down_revision = '5a46707d932d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feature_model')
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_pokes', sa.String(length=120), nullable=True))
        batch_op.drop_column('number_of_features')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_features', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('number_of_pokes')

    op.create_table('feature_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data_set_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], name=op.f('feature_model_ibfk_1')),
    sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], name=op.f('feature_model_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('webhook')
    # ### end Alembic commands ###
