"""creacion modulo elasticsearch

Revision ID: 2de65b1f1aeb
Revises: 93d82f22e6f6
Create Date: 2025-11-14 22:50:25.620650

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2de65b1f1aeb"
down_revision = "7ed375c559ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("elasticsearch", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("elasticsearch")
    # ### end Alembic commands ###
