"""featuremodel a pokemodel

Revision ID: 5a46707d932d
Revises: 2de65b1f1aeb
Create Date: 2025-11-15 15:02:34.866893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a46707d932d'
down_revision = '2de65b1f1aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poke_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_set_id', sa.Integer(), nullable=False),
    sa.Column('fm_meta_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poke_model_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('file_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key('file_ibfk_1', 'poke_model', ['poke_model_id'], ['id'])
        batch_op.drop_column('feature_model_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint('file_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key('file_ibfk_1', 'feature_model', ['feature_model_id'], ['id'])
        batch_op.drop_column('poke_model_id')

    op.drop_table('poke_model')
    # ### end Alembic commands ###
