"""add ds_comment table

Revision ID: a9fa23e932ed
Revises: 93d82f22e6f6
Create Date: 2025-11-18 16:25:08.338706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9fa23e932ed'
down_revision = '93d82f22e6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ds_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poke_filename', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('poke_version', sa.String(length=120), nullable=True))
        batch_op.drop_column('uvl_version')
        batch_op.drop_column('uvl_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('uvl_version', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('poke_version')
        batch_op.drop_column('poke_filename')

    op.drop_table('ds_comment')
    # ### end Alembic commands ###
