# Generated by Selenium IDE (modificado)
import pytest
import os
import pyotp
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait

KNOWN_2FA_SECRET = "5JEIF3ANYS7UJKZEN7PZJFG5RHTNRPR2" 
USER_EMAIL = "test@example.com"
USER_PASSWORD = "test1234"
HOST = "http://127.0.0.1:5000"


@pytest.fixture(scope="module")
def driver():
    """
    Fixture que crea y cierra automáticamente el navegador 
    una vez por módulo de test.
    """
    options = webdriver.FirefoxOptions()
    snap_tmp = os.path.expanduser("~/snap/firefox/common/tmp")
    os.makedirs(snap_tmp, exist_ok=True)
    os.environ["TMPDIR"] = snap_tmp
    
    from webdriver_manager.firefox import GeckoDriverManager
    from selenium.webdriver.firefox.service import Service
    
    service = Service(GeckoDriverManager().install())
    d = webdriver.Firefox(service=service, options=options)
    d.set_window_size(1024, 768)
    yield d
    d.quit()

def test_login2fa(driver):
    
    totp = pyotp.TOTP(KNOWN_2FA_SECRET)

    driver.get(f"{HOST}/")
    driver.set_window_size(1052, 1063)
    
    WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.LINK_TEXT, "Login"))
    ).click()

    WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.ID, "email"))
    )
    driver.find_element(By.ID, "email").send_keys(USER_EMAIL)
    driver.find_element(By.ID, "password").send_keys(USER_PASSWORD)
    
    driver.find_element(By.CSS_SELECTOR, "input[type='submit']").click()

    WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.ID, "token"))
    )
    assert "/login/verify-2fa" in driver.current_url
    
    #Generar el token 2FA válido
    valid_token = totp.now()
    driver.find_element(By.ID, "token").send_keys(valid_token)
    
    driver.find_element(By.CSS_SELECTOR, "input[type='submit']").click()

    WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.LINK_TEXT, "Log out"))
    )
    assert f"{HOST}/" in driver.current_url
    assert "Log out" in driver.page_source
    
    driver.find_element(By.LINK_TEXT, "Log out").click()