# Generated by Selenium IDE
import os
import sys

from selenium.webdriver.common.by import By

from core.selenium.common import close_driver, initialize_driver

sys.path.append(os.getcwd())


class TestCheckearpokes:
    def setup_method(self, method):
        self.driver = initialize_driver()
        self.vars = {}

    def teardown_method(self, method):
        close_driver(self.driver)

    def test_checkearpokes(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1706, 901)
        self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.LINK_TEXT, "My datasets").click()
        self.driver.find_element(By.LINK_TEXT, "Sample dataset 1").click()
        self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.LINK_TEXT, "Upload dataset").click()
        self.driver.find_element(By.LINK_TEXT, "My datasets").click()
        self.driver.find_element(By.LINK_TEXT, "Sample dataset 1").click()
        self.driver.find_element(By.ID, "btnGroupDrop2").click()
        self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
