# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By


class TestCheckearpokes:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_checkearpokes(self):
        self.driver.get("http://localhost:5000/")
        self.driver.set_window_size(1920, 1080)
        self.driver.find_element(By.LINK_TEXT, "Sample dataset 4").click()
        self.driver.find_element(By.ID, "btnGroupDrop34").click()
        self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
        self.driver.find_element(By.ID, "btnGroupDrop35").click()
        self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
        element = self.driver.find_element(By.LINK_TEXT, "Syntax check")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "btnGroupDrop36").click()
        self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
